# Generated by Django 4.2.2 on 2023-07-10 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200, unique=True)),
                (
                    "company_code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("email_id", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=50)),
                ("contact_number", models.BigIntegerField(unique=True)),
                ("company_pan", models.CharField(max_length=16)),
                ("gstin", models.CharField(max_length=16)),
                ("Company_addresss", models.TextField()),
                ("City", models.CharField(max_length=200)),
                ("State", models.CharField(max_length=200)),
                ("pincode", models.BigIntegerField()),
                ("status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delete_status", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Dashbord_view",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_name", models.CharField(max_length=20)),
                ("company_name", models.CharField(max_length=100)),
                ("company_code", models.UUIDField()),
                ("view", models.BooleanField(null=True)),
                ("status", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Invesments_Db",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("company_code", models.UUIDField()),
                ("project", models.CharField(max_length=100)),
                ("project_code", models.UUIDField()),
                ("investor_name", models.CharField(max_length=100)),
                ("investor_code", models.UUIDField()),
                ("wallet_key", models.UUIDField()),
                ("project_share_value", models.BigIntegerField()),
                ("investor_share_count", models.BigIntegerField()),
                ("amount", models.BigIntegerField()),
                ("Payment_given_by", models.CharField(max_length=200)),
                ("Payment_revceiver_name", models.CharField(max_length=200)),
                ("Paid_date", models.DateTimeField(auto_now_add=True)),
                (
                    "First_Approved_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("First_Approved_date", models.DateField(blank=True, null=True)),
                (
                    "Second_Approved_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("Second_Approved_date", models.DateField(blank=True, null=True)),
                ("Createdatetime", models.DateTimeField(auto_now_add=True)),
                ("invesment_start", models.BooleanField()),
                ("invesment_end", models.BooleanField()),
                ("status", models.BooleanField()),
                ("delete_status", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-Paid_date"],
            },
        ),
        migrations.CreateModel(
            name="Investor_menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_name", models.CharField(max_length=20)),
                ("company_name", models.CharField(max_length=100)),
                ("company_code", models.UUIDField()),
                ("view", models.BooleanField(null=True)),
                ("add", models.BooleanField(null=True)),
                ("edit", models.BooleanField(null=True)),
                ("can_delete", models.BooleanField(null=True)),
                ("status", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Investor_Wallet_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_code", models.UUIDField()),
                ("investor_id", models.UUIDField()),
                ("wallet_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("investor_name", models.CharField(max_length=100)),
                ("amount", models.BigIntegerField()),
                ("total_amount", models.BigIntegerField(blank=True, null=True)),
                ("mode_of_payment", models.CharField(max_length=100)),
                ("payment_id", models.CharField(max_length=200)),
                ("payment_given_by", models.CharField(max_length=100)),
                ("payment_receiver_name", models.CharField(max_length=100)),
                (
                    "First_Approved_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("First_Approved_date", models.DateField(blank=True, null=True)),
                (
                    "Second_Approved_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("Second_Approved_date", models.DateField(blank=True, null=True)),
                ("paid_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
                ("delete_status", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-paid_date"],
            },
        ),
        migrations.CreateModel(
            name="Investor_Wallet_History_Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("investor_name", models.CharField(max_length=100)),
                ("reason", models.CharField(max_length=100)),
                ("credited_amount", models.BigIntegerField()),
                ("wallet_key", models.UUIDField()),
                ("credited_time", models.DateTimeField(blank=True)),
                ("debited_amount", models.BigIntegerField()),
                ("debited_date", models.DateTimeField(blank=True)),
                ("total_amount", models.BigIntegerField()),
                ("delete_status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Investor_wallet_menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_name", models.CharField(max_length=20)),
                ("company_name", models.CharField(max_length=100)),
                ("company_code", models.UUIDField()),
                ("view", models.BooleanField(null=True)),
                ("add", models.BooleanField(null=True)),
                ("edit", models.BooleanField(null=True)),
                ("can_delete", models.BooleanField(null=True)),
                ("status", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Investors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_code", models.UUIDField()),
                (
                    "investors_code",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("Display_name", models.CharField(blank=True, max_length=30)),
                ("email_id", models.EmailField(max_length=254)),
                ("user_name", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=255)),
                ("mobile_number", models.CharField(max_length=30)),
                ("Pan_number", models.CharField(max_length=50)),
                ("Aadhar_card_no", models.BigIntegerField(blank=True)),
                ("contact_address", models.TextField()),
                ("City", models.CharField(max_length=200)),
                ("State", models.CharField(max_length=200)),
                ("pincode", models.CharField(max_length=200)),
                ("status", models.BooleanField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("delete_status", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_code", models.UUIDField()),
                ("project_name", models.CharField(max_length=100)),
                (
                    "prject_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("Project_location", models.CharField(max_length=200)),
                ("Latitude", models.FloatField()),
                ("Longitude", models.FloatField()),
                ("Project_value", models.BigIntegerField(blank=True, null=True)),
                (
                    "Kickoff_date",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "Returns_projection_type",
                    models.BigIntegerField(blank=True, null=True),
                ),
                (
                    "Returns_projection_value",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("total_unit_value", models.BigIntegerField(blank=True, null=True)),
                ("blance_unit", models.BigIntegerField(null=True)),
                ("blance_amount", models.BigIntegerField(null=True)),
                ("Other_expense", models.BigIntegerField(blank=True, null=True)),
                ("Total_share", models.BigIntegerField(blank=True, null=True)),
                ("Per_share_value", models.BigIntegerField(blank=True, null=True)),
                ("share_count", models.BigIntegerField(blank=True, null=True)),
                (
                    "Expected_return_date",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("Created_datetime", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(null=True)),
                ("closed_project", models.BooleanField(null=True)),
                ("closed_date", models.DateField(blank=True, null=True)),
                ("delete_status", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-Created_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Project_Exp_menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_name", models.CharField(max_length=20)),
                ("company_name", models.CharField(max_length=100)),
                ("company_code", models.UUIDField()),
                ("view", models.BooleanField(null=True)),
                ("add", models.BooleanField(null=True)),
                ("edit", models.BooleanField(null=True)),
                ("can_delete", models.BooleanField(null=True)),
                ("status", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project_investor_menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_name", models.CharField(max_length=20)),
                ("company_name", models.CharField(max_length=100)),
                ("company_code", models.UUIDField()),
                ("view", models.BooleanField(null=True)),
                ("add", models.BooleanField(null=True)),
                ("edit", models.BooleanField(null=True)),
                ("can_delete", models.BooleanField(null=True)),
                ("status", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project_menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_name", models.CharField(max_length=20)),
                ("company_name", models.CharField(max_length=100)),
                ("company_code", models.UUIDField()),
                ("view", models.BooleanField(null=True)),
                ("add", models.BooleanField(null=True)),
                ("edit", models.BooleanField(null=True)),
                ("can_delete", models.BooleanField(null=True)),
                ("status", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project_Profit_menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_name", models.CharField(max_length=20)),
                ("company_name", models.CharField(max_length=100)),
                ("company_code", models.UUIDField()),
                ("view", models.BooleanField(null=True)),
                ("add", models.BooleanField(null=True)),
                ("edit", models.BooleanField(null=True)),
                ("can_delete", models.BooleanField(null=True)),
                ("status", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project_profit_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_name", models.CharField(max_length=20)),
                ("company_name", models.CharField(max_length=100)),
                ("company_code", models.UUIDField()),
                ("view", models.BooleanField(null=True)),
                ("add", models.BooleanField(null=True)),
                ("edit", models.BooleanField(null=True)),
                ("can_delete", models.BooleanField(null=True)),
                ("status", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project_settlement_menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_name", models.CharField(max_length=20)),
                ("company_name", models.CharField(max_length=100)),
                ("company_code", models.UUIDField()),
                ("view", models.BooleanField(null=True)),
                ("add", models.BooleanField(null=True)),
                ("edit", models.BooleanField(null=True)),
                ("can_delete", models.BooleanField(null=True)),
                ("status", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("company_code", models.UUIDField()),
                ("project_name", models.CharField(max_length=100)),
                ("project_code", models.UUIDField()),
                ("Expense_date", models.DateTimeField(auto_now_add=True)),
                ("amount", models.BigIntegerField()),
                ("Mode_of_payment", models.CharField(max_length=100)),
                ("payment_id", models.CharField(max_length=200)),
                (
                    "First_Approved_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("First_Approved_date", models.DateField(blank=True, null=True)),
                (
                    "Second_Approved_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("Second_Approved_date", models.DateField(blank=True, null=True)),
                ("Createddatetime", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(null=True)),
                ("delete_status", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-Expense_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("company_code", models.UUIDField()),
                ("project_name", models.CharField(max_length=100)),
                ("project_code", models.UUIDField()),
                ("unit_sold", models.BigIntegerField(null=True)),
                ("amount", models.BigIntegerField(null=True)),
                ("blance_unit", models.BigIntegerField(null=True)),
                ("blance_amount", models.BigIntegerField(null=True)),
                (
                    "First_Approved_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("First_Approved_date", models.DateField(blank=True, null=True)),
                (
                    "Second_Approved_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("Second_Approved_date", models.DateField(blank=True, null=True)),
                ("sales_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(null=True)),
                ("delete_status", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-sales_date"],
            },
        ),
        migrations.CreateModel(
            name="Projectsettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("company_code", models.UUIDField()),
                ("investor_name", models.CharField(max_length=100)),
                ("investor_code", models.UUIDField()),
                ("project_name", models.CharField(max_length=100)),
                ("project_code", models.UUIDField()),
                ("wallet_key", models.UUIDField()),
                ("amount", models.BigIntegerField(null=True)),
                ("blance_amount", models.BigIntegerField(null=True)),
                (
                    "First_Approved_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("First_Approved_date", models.DateField(blank=True, null=True)),
                (
                    "Second_Approved_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("Second_Approved_date", models.DateField(blank=True, null=True)),
                ("settlement_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(null=True)),
                ("delete_status", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-settlement_date"],
            },
        ),
        migrations.CreateModel(
            name="Report_view",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_name", models.CharField(max_length=20)),
                ("company_name", models.CharField(max_length=100)),
                ("company_code", models.UUIDField()),
                ("view", models.BooleanField(null=True)),
                ("status", models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("company_code", models.UUIDField()),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("satus", models.BooleanField(default=True)),
                ("delete_status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="User_Registration_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("Display_name", models.CharField(blank=True, max_length=30)),
                ("email_id", models.EmailField(max_length=254, unique=True)),
                ("user_name", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=255)),
                ("mobile_number", models.CharField(max_length=30)),
                ("Pan_number", models.CharField(max_length=50)),
                ("Aadhar_card_no", models.BigIntegerField(blank=True)),
                ("contact_address", models.TextField()),
                ("City", models.CharField(max_length=200)),
                ("State", models.CharField(max_length=200)),
                ("pincode", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="UserLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                ("login_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                ("active_time", models.DurationField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrashedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_data", models.TextField()),
                ("trashed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-trashed_at"],
            },
        ),
        migrations.CreateModel(
            name="staff_logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_code", models.UUIDField()),
                ("username", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("ip_address", models.GenericIPAddressField()),
                ("action", models.CharField(max_length=100)),
                ("action_data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("perment_delete", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="settlement_log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_code", models.UUIDField()),
                ("investor_code", models.UUIDField()),
                ("wallet_key", models.UUIDField()),
                ("ip_address", models.GenericIPAddressField()),
                ("action", models.CharField(max_length=100)),
                ("action_data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("perment_delete", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Sales_log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_code", models.UUIDField()),
                ("project_name", models.CharField(max_length=100)),
                ("project_code", models.UUIDField()),
                ("ip_address", models.GenericIPAddressField()),
                ("action", models.CharField(max_length=100)),
                ("action_data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("perment_delete", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ProjectLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_code", models.UUIDField()),
                ("project_name", models.CharField(max_length=100)),
                ("project_code", models.UUIDField()),
                ("ip_address", models.GenericIPAddressField()),
                ("action", models.CharField(max_length=100)),
                ("action_data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("perment_delete", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="InvestorsWalletLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_code", models.UUIDField()),
                ("investors_code", models.UUIDField()),
                ("investor_name", models.CharField(max_length=100)),
                ("wallet_key", models.UUIDField()),
                ("ip_address", models.GenericIPAddressField()),
                ("action", models.CharField(max_length=100)),
                ("action_data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("perment_delete", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="InvestorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_code", models.UUIDField()),
                ("investors_code", models.UUIDField()),
                ("email_id", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField()),
                ("action", models.CharField(max_length=100)),
                ("action_data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("perment_delete", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Invested_project_Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_code", models.UUIDField()),
                ("project_name", models.CharField(max_length=100)),
                ("project_code", models.UUIDField()),
                ("investor_name", models.CharField(max_length=100)),
                ("investor_code", models.UUIDField()),
                ("ip_address", models.GenericIPAddressField()),
                ("action", models.CharField(max_length=100)),
                ("action_data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("perment_delete", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Expence_log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("company_code", models.UUIDField()),
                ("project_name", models.CharField(max_length=100)),
                ("project_code", models.UUIDField()),
                ("ip_address", models.GenericIPAddressField()),
                ("action", models.CharField(max_length=100)),
                ("action_data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("perment_delete", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="CompanyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_id", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=50)),
                ("company", models.CharField(max_length=200)),
                ("ip_address", models.GenericIPAddressField()),
                ("action", models.CharField(max_length=100)),
                ("action_data", models.JSONField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("perment_delete", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
